api_version = "2024-07"

[[extensions]]
name = "t:name"
handle = "local-discount-code"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

   [extensions.ui.paths]
  create = "/app/local-discount/6134121a-2a46-4f5f-b6b2-eea1ab8d4d00/new"
  details = "/app/local-discount/6134121a-2a46-4f5f-b6b2-eea1ab8d4d00/:id"